spring:
  application:
    name: eureka

server:
  port: 8761
  waitTimeInMsWhenSyncEmpty: 0
  response-cache-update-interval-ms: 5000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka